// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: storeapi/store_api.proto

package storeapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggFunc int32

const (
	AggFunc_AGG_FUNC_COUNT    AggFunc = 0
	AggFunc_AGG_FUNC_SUM      AggFunc = 1
	AggFunc_AGG_FUNC_MIN      AggFunc = 2
	AggFunc_AGG_FUNC_MAX      AggFunc = 3
	AggFunc_AGG_FUNC_AVG      AggFunc = 4
	AggFunc_AGG_FUNC_QUANTILE AggFunc = 5
	AggFunc_AGG_FUNC_UNIQUE   AggFunc = 6
)

// Enum value maps for AggFunc.
var (
	AggFunc_name = map[int32]string{
		0: "AGG_FUNC_COUNT",
		1: "AGG_FUNC_SUM",
		2: "AGG_FUNC_MIN",
		3: "AGG_FUNC_MAX",
		4: "AGG_FUNC_AVG",
		5: "AGG_FUNC_QUANTILE",
		6: "AGG_FUNC_UNIQUE",
	}
	AggFunc_value = map[string]int32{
		"AGG_FUNC_COUNT":    0,
		"AGG_FUNC_SUM":      1,
		"AGG_FUNC_MIN":      2,
		"AGG_FUNC_MAX":      3,
		"AGG_FUNC_AVG":      4,
		"AGG_FUNC_QUANTILE": 5,
		"AGG_FUNC_UNIQUE":   6,
	}
)

func (x AggFunc) Enum() *AggFunc {
	p := new(AggFunc)
	*p = x
	return p
}

func (x AggFunc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggFunc) Descriptor() protoreflect.EnumDescriptor {
	return file_storeapi_store_api_proto_enumTypes[0].Descriptor()
}

func (AggFunc) Type() protoreflect.EnumType {
	return &file_storeapi_store_api_proto_enumTypes[0]
}

func (x AggFunc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggFunc.Descriptor instead.
func (AggFunc) EnumDescriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{0}
}

type Order int32

const (
	Order_ORDER_DESC Order = 0
	Order_ORDER_ASC  Order = 1
)

// Enum value maps for Order.
var (
	Order_name = map[int32]string{
		0: "ORDER_DESC",
		1: "ORDER_ASC",
	}
	Order_value = map[string]int32{
		"ORDER_DESC": 0,
		"ORDER_ASC":  1,
	}
)

func (x Order) Enum() *Order {
	p := new(Order)
	*p = x
	return p
}

func (x Order) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Order) Descriptor() protoreflect.EnumDescriptor {
	return file_storeapi_store_api_proto_enumTypes[1].Descriptor()
}

func (Order) Type() protoreflect.EnumType {
	return &file_storeapi_store_api_proto_enumTypes[1]
}

func (x Order) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Order.Descriptor instead.
func (Order) EnumDescriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{1}
}

type SearchErrorCode int32

const (
	SearchErrorCode_NO_ERROR                      SearchErrorCode = 0
	SearchErrorCode_INGESTOR_QUERY_WANTS_OLD_DATA SearchErrorCode = 1
	SearchErrorCode_TOO_MANY_UNIQ_VALUES          SearchErrorCode = 2
)

// Enum value maps for SearchErrorCode.
var (
	SearchErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "INGESTOR_QUERY_WANTS_OLD_DATA",
		2: "TOO_MANY_UNIQ_VALUES",
	}
	SearchErrorCode_value = map[string]int32{
		"NO_ERROR":                      0,
		"INGESTOR_QUERY_WANTS_OLD_DATA": 1,
		"TOO_MANY_UNIQ_VALUES":          2,
	}
)

func (x SearchErrorCode) Enum() *SearchErrorCode {
	p := new(SearchErrorCode)
	*p = x
	return p
}

func (x SearchErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_storeapi_store_api_proto_enumTypes[2].Descriptor()
}

func (SearchErrorCode) Type() protoreflect.EnumType {
	return &file_storeapi_store_api_proto_enumTypes[2]
}

func (x SearchErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchErrorCode.Descriptor instead.
func (SearchErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{2}
}

type BulkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Docs  []byte `protobuf:"bytes,2,opt,name=docs,proto3" json:"docs,omitempty"`
	Metas []byte `protobuf:"bytes,3,opt,name=metas,proto3" json:"metas,omitempty"`
}

func (x *BulkRequest) Reset() {
	*x = BulkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequest) ProtoMessage() {}

func (x *BulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequest.ProtoReflect.Descriptor instead.
func (*BulkRequest) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{0}
}

func (x *BulkRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BulkRequest) GetDocs() []byte {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *BulkRequest) GetMetas() []byte {
	if x != nil {
		return x.Metas
	}
	return nil
}

type BinaryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BinaryData) Reset() {
	*x = BinaryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryData) ProtoMessage() {}

func (x *BinaryData) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryData.ProtoReflect.Descriptor instead.
func (*BinaryData) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{1}
}

func (x *BinaryData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AggQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field     string    `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	GroupBy   string    `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Func      AggFunc   `protobuf:"varint,4,opt,name=func,proto3,enum=api.AggFunc" json:"func,omitempty"`
	Quantiles []float64 `protobuf:"fixed64,5,rep,packed,name=quantiles,proto3" json:"quantiles,omitempty"`
}

func (x *AggQuery) Reset() {
	*x = AggQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggQuery) ProtoMessage() {}

func (x *AggQuery) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggQuery.ProtoReflect.Descriptor instead.
func (*AggQuery) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{2}
}

func (x *AggQuery) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *AggQuery) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *AggQuery) GetFunc() AggFunc {
	if x != nil {
		return x.Func
	}
	return AggFunc_AGG_FUNC_COUNT
}

func (x *AggQuery) GetQuantiles() []float64 {
	if x != nil {
		return x.Quantiles
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query    string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	From     int64  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To       int64  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Size     int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Offset   int64  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Interval int64  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	// Deprecated: Marked as deprecated in storeapi/store_api.proto.
	Aggregation string `protobuf:"bytes,7,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	Explain     bool   `protobuf:"varint,8,opt,name=explain,proto3" json:"explain,omitempty"`
	WithTotal   bool   `protobuf:"varint,10,opt,name=with_total,json=withTotal,proto3" json:"with_total,omitempty"`
	// Deprecated: Marked as deprecated in storeapi/store_api.proto.
	AggregationFilter string      `protobuf:"bytes,11,opt,name=aggregation_filter,json=aggregationFilter,proto3" json:"aggregation_filter,omitempty"`
	Aggs              []*AggQuery `protobuf:"bytes,12,rep,name=aggs,proto3" json:"aggs,omitempty"`
	Order             Order       `protobuf:"varint,13,opt,name=order,proto3,enum=api.Order" json:"order,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SearchRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SearchRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// Deprecated: Marked as deprecated in storeapi/store_api.proto.
func (x *SearchRequest) GetAggregation() string {
	if x != nil {
		return x.Aggregation
	}
	return ""
}

func (x *SearchRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *SearchRequest) GetWithTotal() bool {
	if x != nil {
		return x.WithTotal
	}
	return false
}

// Deprecated: Marked as deprecated in storeapi/store_api.proto.
func (x *SearchRequest) GetAggregationFilter() string {
	if x != nil {
		return x.AggregationFilter
	}
	return ""
}

func (x *SearchRequest) GetAggs() []*AggQuery {
	if x != nil {
		return x.Aggs
	}
	return nil
}

func (x *SearchRequest) GetOrder() Order {
	if x != nil {
		return x.Order
	}
	return Order_ORDER_DESC
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Marked as deprecated in storeapi/store_api.proto.
	Data      []byte                       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IdSources []*SearchResponse_IdWithHint `protobuf:"bytes,2,rep,name=id_sources,json=idSources,proto3" json:"id_sources,omitempty"`
	Histogram map[uint64]uint64            `protobuf:"bytes,3,rep,name=histogram,proto3" json:"histogram,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Aggs      []*SearchResponse_Agg        `protobuf:"bytes,4,rep,name=aggs,proto3" json:"aggs,omitempty"`
	Total     uint64                       `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Errors    []string                     `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	Code      SearchErrorCode              `protobuf:"varint,7,opt,name=code,proto3,enum=api.SearchErrorCode" json:"code,omitempty"`
	Explain   *ExplainEntry                `protobuf:"bytes,8,opt,name=explain,proto3,oneof" json:"explain,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Marked as deprecated in storeapi/store_api.proto.
func (x *SearchResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchResponse) GetIdSources() []*SearchResponse_IdWithHint {
	if x != nil {
		return x.IdSources
	}
	return nil
}

func (x *SearchResponse) GetHistogram() map[uint64]uint64 {
	if x != nil {
		return x.Histogram
	}
	return nil
}

func (x *SearchResponse) GetAggs() []*SearchResponse_Agg {
	if x != nil {
		return x.Aggs
	}
	return nil
}

func (x *SearchResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SearchResponse) GetCode() SearchErrorCode {
	if x != nil {
		return x.Code
	}
	return SearchErrorCode_NO_ERROR
}

func (x *SearchResponse) GetExplain() *ExplainEntry {
	if x != nil {
		return x.Explain
	}
	return nil
}

type ExplainEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Duration *durationpb.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Children []*ExplainEntry      `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *ExplainEntry) Reset() {
	*x = ExplainEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExplainEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainEntry) ProtoMessage() {}

func (x *ExplainEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainEntry.ProtoReflect.Descriptor instead.
func (*ExplainEntry) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{5}
}

func (x *ExplainEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExplainEntry) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ExplainEntry) GetChildren() []*ExplainEntry {
	if x != nil {
		return x.Children
	}
	return nil
}

type IdWithHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hint string `protobuf:"bytes,2,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *IdWithHint) Reset() {
	*x = IdWithHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdWithHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdWithHint) ProtoMessage() {}

func (x *IdWithHint) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdWithHint.ProtoReflect.Descriptor instead.
func (*IdWithHint) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{6}
}

func (x *IdWithHint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdWithHint) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type FetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids          []string      `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Explain      bool          `protobuf:"varint,3,opt,name=explain,proto3" json:"explain,omitempty"`
	IdsWithHints []*IdWithHint `protobuf:"bytes,4,rep,name=ids_with_hints,json=idsWithHints,proto3" json:"ids_with_hints,omitempty"`
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{7}
}

func (x *FetchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *FetchRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *FetchRequest) GetIdsWithHints() []*IdWithHint {
	if x != nil {
		return x.IdsWithHints
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{8}
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldestTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=oldest_time,json=oldestTime,proto3" json:"oldest_time,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetOldestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestTime
	}
	return nil
}

type SearchResponse_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid uint64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Rid uint64 `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
}

func (x *SearchResponse_Id) Reset() {
	*x = SearchResponse_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Id) ProtoMessage() {}

func (x *SearchResponse_Id) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Id.ProtoReflect.Descriptor instead.
func (*SearchResponse_Id) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchResponse_Id) GetMid() uint64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SearchResponse_Id) GetRid() uint64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type SearchResponse_IdWithHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *SearchResponse_Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hint string             `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *SearchResponse_IdWithHint) Reset() {
	*x = SearchResponse_IdWithHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse_IdWithHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_IdWithHint) ProtoMessage() {}

func (x *SearchResponse_IdWithHint) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_IdWithHint.ProtoReflect.Descriptor instead.
func (*SearchResponse_IdWithHint) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SearchResponse_IdWithHint) GetId() *SearchResponse_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SearchResponse_IdWithHint) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type SearchResponse_Histogram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min       float64   `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max       float64   `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	Sum       float64   `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Total     int64     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	NotExists int64     `protobuf:"varint,5,opt,name=not_exists,json=notExists,proto3" json:"not_exists,omitempty"`
	Samples   []float64 `protobuf:"fixed64,6,rep,packed,name=samples,proto3" json:"samples,omitempty"`
}

func (x *SearchResponse_Histogram) Reset() {
	*x = SearchResponse_Histogram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse_Histogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Histogram) ProtoMessage() {}

func (x *SearchResponse_Histogram) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Histogram.ProtoReflect.Descriptor instead.
func (*SearchResponse_Histogram) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{4, 2}
}

func (x *SearchResponse_Histogram) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *SearchResponse_Histogram) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *SearchResponse_Histogram) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *SearchResponse_Histogram) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse_Histogram) GetNotExists() int64 {
	if x != nil {
		return x.NotExists
	}
	return 0
}

func (x *SearchResponse_Histogram) GetSamples() []float64 {
	if x != nil {
		return x.Samples
	}
	return nil
}

type SearchResponse_Agg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Marked as deprecated in storeapi/store_api.proto.
	Agg          map[string]uint64                    `protobuf:"bytes,1,rep,name=agg,proto3" json:"agg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AggHistogram map[string]*SearchResponse_Histogram `protobuf:"bytes,2,rep,name=agg_histogram,json=aggHistogram,proto3" json:"agg_histogram,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NotExists    int64                                `protobuf:"varint,3,opt,name=not_exists,json=notExists,proto3" json:"not_exists,omitempty"`
}

func (x *SearchResponse_Agg) Reset() {
	*x = SearchResponse_Agg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storeapi_store_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse_Agg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Agg) ProtoMessage() {}

func (x *SearchResponse_Agg) ProtoReflect() protoreflect.Message {
	mi := &file_storeapi_store_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Agg.ProtoReflect.Descriptor instead.
func (*SearchResponse_Agg) Descriptor() ([]byte, []int) {
	return file_storeapi_store_api_proto_rawDescGZIP(), []int{4, 3}
}

// Deprecated: Marked as deprecated in storeapi/store_api.proto.
func (x *SearchResponse_Agg) GetAgg() map[string]uint64 {
	if x != nil {
		return x.Agg
	}
	return nil
}

func (x *SearchResponse_Agg) GetAggHistogram() map[string]*SearchResponse_Histogram {
	if x != nil {
		return x.AggHistogram
	}
	return nil
}

func (x *SearchResponse_Agg) GetNotExists() int64 {
	if x != nil {
		return x.NotExists
	}
	return 0
}

var File_storeapi_store_api_proto protoreflect.FileDescriptor

var file_storeapi_store_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x0b, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x22, 0x20, 0x0a, 0x0a,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x81,
	0x01, 0x0a, 0x08, 0x41, 0x67, 0x67, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x79, 0x12, 0x20, 0x0a, 0x04,
	0x66, 0x75, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x67, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x52, 0x04, 0x66, 0x75, 0x6e, 0x63, 0x12, 0x1c,
	0x0a, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x4a, 0x04, 0x08, 0x02,
	0x10, 0x03, 0x22, 0xe8, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52,
	0x0b, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x31, 0x0a, 0x12, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x11, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x04, 0x61, 0x67, 0x67, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x67, 0x67,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x04, 0x61, 0x67, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0xf8, 0x07,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x49, 0x64, 0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x69, 0x64,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x2b, 0x0a, 0x04, 0x61, 0x67, 0x67,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x67, 0x67,
	0x52, 0x04, 0x61, 0x67, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x30,
	0x0a, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x48, 0x00, 0x52, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x88, 0x01, 0x01,
	0x1a, 0x28, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x72, 0x69, 0x64, 0x1a, 0x48, 0x0a, 0x0a, 0x49, 0x64,
	0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x69, 0x6e, 0x74, 0x1a, 0x90, 0x01, 0x0a, 0x09, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x6e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x1a, 0xc4, 0x02, 0x0a, 0x03, 0x41, 0x67, 0x67, 0x12,
	0x36, 0x0a, 0x03, 0x61, 0x67, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x67, 0x67, 0x2e, 0x41, 0x67, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x03, 0x61, 0x67, 0x67, 0x12, 0x4e, 0x0a, 0x0d, 0x61, 0x67, 0x67, 0x5f, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x41, 0x67, 0x67, 0x2e, 0x41, 0x67, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x61, 0x67, 0x67, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x74, 0x5f, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x6f, 0x74,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x41, 0x67, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x5e,
	0x0a, 0x11, 0x41, 0x67, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3c,
	0x0a, 0x0e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x45, 0x78, 0x70,
	0x6c, 0x61, 0x69, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x0a, 0x49, 0x64, 0x57,
	0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x22, 0x71, 0x0a, 0x0c, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x0e, 0x69, 0x64, 0x73, 0x5f, 0x77,
	0x69, 0x74, 0x68, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x64, 0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74,
	0x52, 0x0c, 0x69, 0x64, 0x73, 0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4d, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x2a, 0x91,
	0x01, 0x0a, 0x07, 0x41, 0x67, 0x67, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x47,
	0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x5f, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x5f, 0x53, 0x55, 0x4d, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x5f, 0x4d, 0x49, 0x4e,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x5f, 0x4d,
	0x41, 0x58, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43,
	0x5f, 0x41, 0x56, 0x47, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55,
	0x4e, 0x43, 0x5f, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x13, 0x0a,
	0x0f, 0x41, 0x47, 0x47, 0x5f, 0x46, 0x55, 0x4e, 0x43, 0x5f, 0x55, 0x4e, 0x49, 0x51, 0x55, 0x45,
	0x10, 0x06, 0x2a, 0x26, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x0a, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x53, 0x43, 0x10, 0x01, 0x2a, 0x5c, 0x0a, 0x0f, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x49,
	0x4e, 0x47, 0x45, 0x53, 0x54, 0x4f, 0x52, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x57, 0x41,
	0x4e, 0x54, 0x53, 0x5f, 0x4f, 0x4c, 0x44, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x18,
	0x0a, 0x14, 0x54, 0x4f, 0x4f, 0x5f, 0x4d, 0x41, 0x4e, 0x59, 0x5f, 0x55, 0x4e, 0x49, 0x51, 0x5f,
	0x56, 0x41, 0x4c, 0x55, 0x45, 0x53, 0x10, 0x02, 0x32, 0xd9, 0x01, 0x0a, 0x08, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x41, 0x70, 0x69, 0x12, 0x32, 0x0a, 0x04, 0x42, 0x75, 0x6c, 0x6b, 0x12, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f,
	0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x33, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f,
	0x7a, 0x6f, 0x6e, 0x2e, 0x72, 0x75, 0x2f, 0x73, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x71, 0x2d, 0x64,
	0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x61, 0x70, 0x69, 0x3b, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storeapi_store_api_proto_rawDescOnce sync.Once
	file_storeapi_store_api_proto_rawDescData = file_storeapi_store_api_proto_rawDesc
)

func file_storeapi_store_api_proto_rawDescGZIP() []byte {
	file_storeapi_store_api_proto_rawDescOnce.Do(func() {
		file_storeapi_store_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_storeapi_store_api_proto_rawDescData)
	})
	return file_storeapi_store_api_proto_rawDescData
}

var file_storeapi_store_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_storeapi_store_api_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_storeapi_store_api_proto_goTypes = []any{
	(AggFunc)(0),                      // 0: api.AggFunc
	(Order)(0),                        // 1: api.Order
	(SearchErrorCode)(0),              // 2: api.SearchErrorCode
	(*BulkRequest)(nil),               // 3: api.BulkRequest
	(*BinaryData)(nil),                // 4: api.BinaryData
	(*AggQuery)(nil),                  // 5: api.AggQuery
	(*SearchRequest)(nil),             // 6: api.SearchRequest
	(*SearchResponse)(nil),            // 7: api.SearchResponse
	(*ExplainEntry)(nil),              // 8: api.ExplainEntry
	(*IdWithHint)(nil),                // 9: api.IdWithHint
	(*FetchRequest)(nil),              // 10: api.FetchRequest
	(*StatusRequest)(nil),             // 11: api.StatusRequest
	(*StatusResponse)(nil),            // 12: api.StatusResponse
	(*SearchResponse_Id)(nil),         // 13: api.SearchResponse.Id
	(*SearchResponse_IdWithHint)(nil), // 14: api.SearchResponse.IdWithHint
	(*SearchResponse_Histogram)(nil),  // 15: api.SearchResponse.Histogram
	(*SearchResponse_Agg)(nil),        // 16: api.SearchResponse.Agg
	nil,                               // 17: api.SearchResponse.HistogramEntry
	nil,                               // 18: api.SearchResponse.Agg.AggEntry
	nil,                               // 19: api.SearchResponse.Agg.AggHistogramEntry
	(*durationpb.Duration)(nil),       // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 22: google.protobuf.Empty
}
var file_storeapi_store_api_proto_depIdxs = []int32{
	0,  // 0: api.AggQuery.func:type_name -> api.AggFunc
	5,  // 1: api.SearchRequest.aggs:type_name -> api.AggQuery
	1,  // 2: api.SearchRequest.order:type_name -> api.Order
	14, // 3: api.SearchResponse.id_sources:type_name -> api.SearchResponse.IdWithHint
	17, // 4: api.SearchResponse.histogram:type_name -> api.SearchResponse.HistogramEntry
	16, // 5: api.SearchResponse.aggs:type_name -> api.SearchResponse.Agg
	2,  // 6: api.SearchResponse.code:type_name -> api.SearchErrorCode
	8,  // 7: api.SearchResponse.explain:type_name -> api.ExplainEntry
	20, // 8: api.ExplainEntry.duration:type_name -> google.protobuf.Duration
	8,  // 9: api.ExplainEntry.children:type_name -> api.ExplainEntry
	9,  // 10: api.FetchRequest.ids_with_hints:type_name -> api.IdWithHint
	21, // 11: api.StatusResponse.oldest_time:type_name -> google.protobuf.Timestamp
	13, // 12: api.SearchResponse.IdWithHint.id:type_name -> api.SearchResponse.Id
	18, // 13: api.SearchResponse.Agg.agg:type_name -> api.SearchResponse.Agg.AggEntry
	19, // 14: api.SearchResponse.Agg.agg_histogram:type_name -> api.SearchResponse.Agg.AggHistogramEntry
	15, // 15: api.SearchResponse.Agg.AggHistogramEntry.value:type_name -> api.SearchResponse.Histogram
	3,  // 16: api.StoreApi.Bulk:input_type -> api.BulkRequest
	6,  // 17: api.StoreApi.Search:input_type -> api.SearchRequest
	10, // 18: api.StoreApi.Fetch:input_type -> api.FetchRequest
	11, // 19: api.StoreApi.Status:input_type -> api.StatusRequest
	22, // 20: api.StoreApi.Bulk:output_type -> google.protobuf.Empty
	7,  // 21: api.StoreApi.Search:output_type -> api.SearchResponse
	4,  // 22: api.StoreApi.Fetch:output_type -> api.BinaryData
	12, // 23: api.StoreApi.Status:output_type -> api.StatusResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_storeapi_store_api_proto_init() }
func file_storeapi_store_api_proto_init() {
	if File_storeapi_store_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storeapi_store_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BulkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BinaryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AggQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ExplainEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*IdWithHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse_IdWithHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse_Histogram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storeapi_store_api_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SearchResponse_Agg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_storeapi_store_api_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storeapi_store_api_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storeapi_store_api_proto_goTypes,
		DependencyIndexes: file_storeapi_store_api_proto_depIdxs,
		EnumInfos:         file_storeapi_store_api_proto_enumTypes,
		MessageInfos:      file_storeapi_store_api_proto_msgTypes,
	}.Build()
	File_storeapi_store_api_proto = out.File
	file_storeapi_store_api_proto_rawDesc = nil
	file_storeapi_store_api_proto_goTypes = nil
	file_storeapi_store_api_proto_depIdxs = nil
}
