{
 "title": "seq-db | elastic | vlogs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "containers_selector",
    "query": ".*(vlogs|elastic|seq-db|seq-proxy).*"
   },
   {
    "name": "containers",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{name!=\"\",}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Output Rate (docs/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_elasticsearch_input_events_count[$__rate_interval]))",
     "legendFormat": "Elasticsearch"
    },
    {
     "expr": "sum(rate(file_d_pipeline_seqdb_input_events_count[$__rate_interval]))",
     "legendFormat": "seq-db"
    }
   ]
  },
  {
   "title": "Output Rate (MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(file_d_pipeline_elasticsearch_output_events_size[$__rate_interval]))",
     "legendFormat": "Elasticsearch"
    },
    {
     "expr": "sum(rate(file_d_pipeline_seqdb_output_events_size[$__rate_interval]))",
     "legendFormat": "seq-db"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\"})) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$containers\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_disk_usage_bytes{path=~\"$containers_selector\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[$__rate_interval])) by (le,system))",
     "legendFormat": "99q | {{system}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[$__rate_interval])) by (le,system))",
     "legendFormat": "95q | {{system}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(request_duration_seconds_bucket[$__rate_interval])) by (le,system))",
     "legendFormat": "90q | {{system}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(request_duration_seconds_bucket[$__rate_interval])) by (le,system))",
     "legendFormat": "75q | {{system}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_duration_seconds_bucket[$__rate_interval])) by (le,system))",
     "legendFormat": "50q | {{system}}"
    }
   ]
  },
  {
   "title": "Search RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(search_generator_requests[$__rate_interval])) by (system)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Search Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(search_generator_request_errors[$__rate_interval])) by (system)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}